unique_ids:
  assets:
    standard-page.html: IR7XBF2KEN6O735X5PPOXFBIHLN4EHTR
    theme.css: 7K2TS3FRRFJX5IN5HEAVF3KAZJ7UDEOL
  forms:
    Form1: 2BEDFUHZ2ZS3UHFVOU7TEEUPTKR6VU3Q
  modules: {}
  scripts: {}
  server_modules: {}
